apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-integration
  labels:
    app: devops-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-integration
  template:
    metadata:
      labels:
        app: devops-integration
    spec:
      containers:
      - name: devops-integration-javaserver
        image: madhublue01/devops-integration:latest
        ports:
        - containerPort: 8080              

apiVersion: v1
kind: Service
metadata:
  name: devops-integration-service
spec:
  selector:
    app: devops-integration
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 32000
